---
editor_options: 
  markdown: 
    wrap: 72
---

# **Deliverable Management and Quality Assurance**

The iRISE SharePoint includes [General/Deliverables Submitted
Folder](https://charitede.sharepoint.com/:f:/r/sites/iRISE/Shared%20Documents/General/Deliverables%20submitted?csf=1&web=1&e=i2hJoz).
A subfolder has been created for each deliverable (named
[Dx.y_max3words_deliverable_name]). All PUBLIC deliverables in iRISE
will automatically be published in CORDIS following submission. This
should be kept in mind when preparing deliverables for submission.

## Deliverable Document Structure and Style

Deliverables must use the [Deliverable
Template](https://charitede.sharepoint.com/:w:/r/sites/iRISE/Shared%20Documents/General/iRISE%20Dissemination_Communication_Templates/Templates/DeliverableTemplate.docx?d=w4ec2474158ab425f86655df0f923297d&csf=1&web=1&e=drgFm9).
Its style (including fonts, colours, headers/footers, numbering of
headings) and structure must be maintained. The following general
structure should be followed and is as such provided in the deliverable
template of the project:

-   Cover page (project title, title of deliverable, date, lead
    beneficiary, authors, reviewers)\
-   Document Information and Revision History (information table,
    revision history table)\
-   Table of Contents\
-   Executive Summary\
-   List of Abbreviations\
-   Core part\
-   Acknowledgements\
-   References\
-   Annexes (optional)

## Internal Review Process and Deadlines for Deliverables

The lead author (task lead) is responsible for submitting the
deliverable by ensuring the latest version is stored within the
respective folder in Microsoft Teams/SharePoint and informing the
Consortium via email within the deadline (as described below). All
deliverables will be reviewed internally in the Consortium.
Content/research deliverables will be reviewed by two project partners
not or only marginally involved in the creation of the deliverable.
Reviewers must ensure that all content is consistent with the provided
summary, the objectives of the deliverable, are scientifically correct
and of high quality. In addition, the reviewers should also perform
proof-reading and grammar checks. The reviewer must provide comments or
modifications using the track changes features. The assigned reviewers
and deadlines for all deliverables are detailed in Table 2. The [iRISE
PM
Planner](https://tasks.office.com/charitede.onmicrosoft.com/en-US/Home/Planner/#/plantaskboard?groupId=63cd0d10-aa1b-4db9-9bb0-ed23b58ec69b&planId=P4fliqzuUEeyiZo6z3Z3L5YAAegq)
also details the deadlines and responsible individuals for each
deliverable and milestone.

The lead author and their partner institution are then responsible for
ensuring that all reviewer comments are addressed in a timely fashion to
ensure submission to the EC by the official delivery date. All
deliverables will be uploaded to the EC Participant Portal by Sarah
McCann. Hence, lead authors should ensure that the final deliverable is
stored within the dedicated Microsoft Teams folder and inform the
coordinating partner <u>**at least two days**</u> in advance of the
final submission date.

Table 1 presents the timeline for the deliverable review process in
terms of weeks and days before the due date. The due date always
corresponds to the last date of the month number indicated in the
[Description of
Action](https://charitede.sharepoint.com/:b:/r/sites/iRISE/Shared%20Documents/General/Grant%20Agreement/GA%20amendment%20Sept.%202023/iRISE_Annex1B_DoA_2023-09-25_v4_clean.pdf?csf=1&web=1&e=CGlIBC).
Meanwhile Table 2 presents the responsible reviewer and partner
institution for each Deliverable. As with the case of a change in
researchers participating in the project, if any of the identified
reviewers ceases to participate in iRISE, the partner institution is
responsible for re-assigning a reviewer within their structure and
propose the change to the project co-coordinators, who will either
approve the change or assign the review to another iRISE member whose
knowledge is adequate for the task at hand.

***Table 1**: Timeline for deliverable review process*

|                         |                                                                                                         |
|-------------------------|---------------------------------------------------------------------------------------------------------|
| 1 calendar month before | Deliverable report is available for review in respective MS Teams folder                                |
|                         | WP lead(s) send email to designated reviewers to inform them the doc is ready for review                |
|                         | Corresponding WP mailing list is used to inform all WP members that they are able to review and comment |
| 10^th^ of the month     | Reviews are available in Teams doc                                                                      |
| 17^th^ of the month     | Lead author completes cycle of revisions                                                                |
|                         | Whole consortium is able to comment and give approval                                                   |
| 2 days before           | Final version is available on MS Teams                                                                  |
|                         | WP lead(s) do final quality check                                                                       |
| Due date                | Deliverable submitted to the Commission by Sarah                                                        |

***Table 2**: Assigned reviewers and deadlines for deliverables*

|        |                                                                                                                                                                                  |                          |          |                |                            |                          |                  |
|:-------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------|:---------|:---------------|:---------------------------|:-------------------------|:-----------------|
| **ID** | **Deliverable name**                                                                                                                                                             | **Lead**                 | **Type** | **Due Date**   | **Internal delivery date** | **R1**                   | **R2**           |
| D7.1   | Project Website                                                                                                                                                                  | Mattera (MIK)            | DEC      | 31/10/<br>2023 | 30/09/<br>2023             | Nilsonne (KI)            | \-               |
| D6.2   | Data Management Plan                                                                                                                                                             | Currie (UEDIN)           | DMP      | 29/02/<br>2024 | 31/01/<br>2024             | Miller (MIK)             | McCann (Charité) |
| D6.1   | Dissemination and exploitation Plan                                                                                                                                              | Currie (UEDIN)           | R        | 29/02/<br>2024 | 31/01/<br>2024             | Zellers (UH)             | Sena (UEDIN)     |
| D5.1   | Study protocols for interventions registered                                                                                                                                     | Heyard (UZH)             | R        | 29/02/<br>2024 | 31/01/<br>2024             | Fanelli (HW)             | McCann (Charité) |
| D1.1   | Glossary of common terminology resulting from scoping reviews                                                                                                                    | Würbel (UBERN)           | R        | 30/06/<br>2024 | 31/05/<br>2024             | Hair (UEDIN)             | Sena (UEDIN)     |
| D2.1   | Completed iRISE-SOLES of interventions to improve reproducibility                                                                                                                | Hair (UEDIN)             | DEC      | 31/08/<br>2024 | 31/07/<br>2024             | Würbel (UBERN)           | Miller (MIK)     |
| D2.2   | Registration of protocol for systematic review of interventions that have been tested for effectiveness                                                                          | McCann (Charité)         | R        | 30/11/<br>2024 | 31/10/<br>2024             | Gerlach (GoEQIPD)        | Heyard (UZH)     |
| D3.1   | Interim best practice guidelines for embedding and mainstreaming EDI considerations into tool development and interventions in the reproducibility space                         | Salholz-Hillel (Charité) | R        | 28/02/<br>2025 | 31/01/<br>2025             | Wever (RUMC)             | Sena (UEDIN)     |
| D1.2   | Interim report with main results from simulation studies, modelling and empirical analyses to diagnose and prevent irreproducibility, and testing of meta-scientific predictions | Fanelli (HW)             | R        | 28/02/<br>2025 | 31/01/<br>2025             | Wever (RUMC)             | McCann (Charité) |
| D6.3   | Dissemination and exploitation including communication activities plan update                                                                                                    | Currie (UEDIN)           | R        | 28/02/<br>2025 | 31/01/<br>2025             | Heyard (UZH)             | Sena (UEDIN)     |
| D6.4   | Interim policy brief                                                                                                                                                             | Currie (UEDIN)           | R        | 28/02/<br>2025 | 31/01/<br>2025             | Marušić (MFEST)          | McCann (Charité) |
| D4.1   | Interim report on facilitators and barriers to implementation of interventions and practices                                                                                     | Marušić (MFEST)          | R        | 28/02/<br>2025 | 31/01/<br>2025             | Wever (RUMC)             | Sena (UEDIN)     |
| D4.3   | Final report on facilitators and barriers to implementation of interventions and practices                                                                                       | Marušić (MFEST)          | R        | 28/02/<br>2026 | 31/01/<br>2026             | Wever (RUMC)             | McCann (Charité) |
| D4.2   | Priority list of interventions and practices, integrated in The Embassy of Good Science                                                                                          | Marušić (MFEST)          | DEC      | 28/02/<br>2026 | 31/01/<br>2026             | Miller (MIK)             | Sena (UEDIN)     |
| D5.2   | Report on results from automated screening tools intervention                                                                                                                    | Weissgerber (Charité)    | R        | 28/02/<br>2026 | 31/01/<br>2026             | Currie (UEDIN)           | Sena (UEDIN)     |
| D5.3   | Report on results from computational reproducibility review intervention                                                                                                         | Nilsonne (KI)            | R        | 28/02/<br>2026 | 31/01/<br>2026             | Hair (UEDIN)             | McCann (Charité) |
| D5.4   | Report on results from EQIPD Quality System intervention                                                                                                                         | Gerlach (GoEQIPD)        | R        | 28/02/<br>2026 | 31/01/<br>2026             | Marušić (MFEST)          | McCann (Charité) |
| D5.5   | Report on results from statistical interventions analysis                                                                                                                        | Würbel (UBERN)           | R        | 28/02/<br>2026 | 31/01/<br>2026             | Fanelli (HW)             | Sena (UEDIN)     |
| D3.2   | Summary of cross-cutting "support activities" throughout the project                                                                                                             | Zellers (UH)             | R        | 31/05/<br>2026 | 30/04/<br>2026             | Nilsonne (KI)            | Sena (UEDIN)     |
| D6.5   | Online portal of Implementation Guide summaries                                                                                                                                  | Currie (UEDIN)           | DEC      | 31/05/<br>2026 | 30/04/<br>2026             | Fanelli (HW)             | McCann (Charité) |
| D2.3   | Completed systematic reviews of interventions that have been tested for effectiveness                                                                                            | McCann (Charité)         | R        | 31/05/<br>2026 | 30/04/<br>2026             | Nilsonne (KI)            | Miller (MIK)     |
| D3.3   | Best practice guidelines for embedding and mainstreaming EDI considerations into tool development and interventions in the reproducibility space                                 | Salholz-Hillel (Charité) | R        | 30/06/<br>2026 | 31/05/<br>2026             | Marušić (MFEST)          | Sena (UEDIN)     |
| D6.8   | Final reflection report of the iRISE experience                                                                                                                                  | Currie (UEDIN)           | R        | 31/08/<br>2026 | 31/07/<br>2026             | Heyard (UZH)             | McCann (Charité) |
| D2.4   | Completed framework to evaluate interventions for reproducibility in the context of systematic reviews                                                                           | McCann (Charité)         | R        | 31/08/<br>2026 | 31/07/<br>2026             | Fanelli (HW)             | Miller (MIK)     |
| D1.3   | Summary report with main results from simulation studies, modelling and empirical analyses to diagnose and prevent irreproducibility, and testing of meta-scientific predictions | Heyard (UZH)             | R        | 31/08/<br>2026 | 31/07/<br>2026             | Weissgerber (Charité)    | Sena (UEDIN)     |
| D6.7   | Final policy brief                                                                                                                                                               | Currie (UEDIN)           | R        | 31/08/<br>2026 | 31/07/<br>2026             | Salholz-Hillel (Charité) | McCann (Charité) |

## File Naming

For the draft phase: Dx.y_max3words_deliverable_name_DRAFT_n.0.docx\
For the review phase: Dx.y_max3words_deliverable_name_REVIEW_n.0.docx\
For the final version, we will use:
iRISE_Dx.y_max3words_deliverable_name.docx\
n.0 should start with 1.0 and update in instances where new versions are
saved.\
Authors and reviewers must be identified in the document revision
history table on the second page of each deliverable.
