# **Key Performance Indicators for Impact**

The major key performance indicators for impact for iRISE are listed in Table 4. The pilot activities will be revised in accordance with the evolving co-creation strategy. Corresponding performance indicators might therefore be subject to change and in some instances, they are being defined during M1-5 of the project, hence at the time of the initial publication of this PM Handbook they are not complete. The project coordinator will monitor reasonable progress towards the key performance indicators throughout the project.\

A detailed description of iRISE's pathway to impact can be found in the [iRISE Grant Agreement](https://charitede.sharepoint.com/:b:/r/sites/iRISE/Shared%20Documents/General/Grant%20Agreement/Amendment%20-%20AMD-101094853-4_Grant%20Agreement%20iRISE.pdf?csf=1&web=1&e=SqVvdc).

_**Table 4**: Key Performance Indicators for Impact_

+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
|                                                                           | **Success measure**                                  | **KPI**     |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| **Pilot activities**                                                      |                                                      |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| Structured understanding of reproducibility                               | Glossary                                             |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
|                                                                           | Theory Output                                        |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| Catalogue interventions to improve reproducibility across all disciplines |                                                      |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| Evidence-based guidelines of best practice                                | No. of final guidelines published                    |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| Assessment and summary of interventions' effectiveness                    | Systematic reviews                                   |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
|                                                                           | No. of interventions tested, integrating an EDI lens | 4           |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| **Dissemination**                                                         |                                                      |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| Protocols and study results                                               | No. of Review Protocols registered                   |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
|                                                                           | No. Study Protocols registered                       |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| Open knowledge base                                                       |                                                      |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| iRISE-SOLES                                                               |                                                      |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| iRISE Framework                                                           |                                                      |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| Training materials                                                        |                                                      |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| Social media                                                              | No. of Press Releases                                |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
|                                                                           | No. of X posts                                       |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
| Website                                                                   | No. of Visits                                        |             |
+---------------------------------------------------------------------------+------------------------------------------------------+-------------+
