# **Appendix 1: Ethical Self-Assessment and Ethical Risks Identification**

## Ethics self-assessment

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Ethical Areas inherent to the Project**                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                         | **Yes** | **No** | **Information to be provided in the proposal**                                                                                                                                                                                                                                                                                                                                | **Documents to be** <br>**kept on file and provided upon request**                                                                                                                                                                                                                         |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| HUMANS                                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                                                         |         |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does your activity involve human participants?                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                         | X       |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| If yes                                                                                                                                                                                                                                                                                                    | Are they volunteers?                                                                                                                                                                                                    | X       |        | Participation from members of partner institutions is managed by each partner following ethical guidelines and voluntary adhesion to iRISE while external stakeholders will voluntarily sign an informed explicit consent to partake in iRISE.                                                                                                                                | Signed consent for external participants.                                                                                                                                                                                                                                                  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                           | Are they healthy volunteers for medical studies?                                                                                                                                                                        |         | X      |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                           | Are they patients for medical studies?                                                                                                                                                                                  |         | X      |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                           | Are they potentially vulnerable individuals or groups?                                                                                                                                                                  |         | X      |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                           | Are they children/minors?                                                                                                                                                                                               |         | X      | If this were to change throughout the Project, it is necessary to require explicit consent from parents following the same procedure as for individual adult's consent.                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                           | Are there other persons unable to give informed consent?                                                                                                                                                                |         | X      |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does your activity involve interventions (physical also including imagining technology, behavioural treatments, tracking and tracing, etc.) on the study of participants?                                                                                                                                 |                                                                                                                                                                                                                         |         | X      |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| If yes                                                                                                                                                                                                                                                                                                    | Does it involve invasive techniques (e.g., collection of human cells or tissues, surgical or medical interventions, invasive studies on the brain, TMS, etc.)?                                                          | N/A     |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                           | Does it involve collection of biological samples?                                                                                                                                                                       | N/A     |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does your activity involve conducting a clinical study as defined by the Clinical Trial - Regulation 536/2014 (using pharmaceuticals, biologicals, radiopharmaceuticals, or advanced therapy medicinal products)?                                                                                         |                                                                                                                                                                                                                         | N/A     |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PROTECTION OF PERSONAL DATA                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                         |         |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does your activity involve processing of personal data?                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                         | X       |        | Detailed information regarding iRISE's specific data management included in the Data Management Plan                                                                                                                                                                                                                                                                          | DMP (including Data Protection Impact Assessment)                                                                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                         |         |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                         |         |        |                                                                                                                                                                                                                                                                                                                                                                               | Informed consent <br>forms and information <br>sheets                                                                                                                                                                                                                                      |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| If yes                                                                                                                                                                                                                                                                                                    | Does it involve the processing of special categories of personal data (e.g., sexual lifestyle, ethnicity, genetic, biometric and health data, political opinion, religious or philosophical beliefs)?                   | X       |        | WP3 is interested in equity, diversity and inclusion, and research culture and the impact of these domains on reproducibility. These exercises will therefore include collection and assessment of the impact of gender and potentially ethnicity in the reproducibility domain.                                                                                              |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                           | Does it involve processing of genetic, biometric or health data?                                                                                                                                                        |         | X      |                                                                                                                                                                                                                                                                                                                                                                               | Declaration of confirming <br>compliance with the laws of the country where the data will be collected.                                                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                                                                                           | Does it involve profiling, systematic monitoring of individuals, or processing of large-scale of special categories of data or intrusive methods of data processing (such as surveillance, geolocation tracking, etc.)? |         | X      | Details of the methods used for tracking/profiling, assessment of the ethics risks related to those data processing operations, explanation as to how the rights/freedoms of the participants/subjects will be safeguarded and how they will be informed.                                                                                                                     | Opinion of the data controller for conducting DPIA - <br>DMP                                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does your activity involve further processing of previously collected personal data (including use of pre-existing data sets or sources, merging existing data sets)?                                                                                                                                     |                                                                                                                                                                                                                         |         | X      | Details of the original data set, including how rights will be safeguarded, how processed data is limited to the purposes of the Project and relevant to its objectives, and/or justification why data will not be anonymised or pseudonymised (if relevant)                                                                                                                  | Confirmation that the data controller has a lawful basis for the data processing and adequate technical/<br>organisational <br>measures are in place to safeguard the rights of the data subjects including permission by the owner/manager of the data sets (e.g. social media databases) |
|                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                         |         |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                         |         |        |                                                                                                                                                                                                                                                                                                                                                                               | Informed consent/information sheets and other applicable documents                                                                                                                                                                                                                         |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Is it planned to import personal data (data transfer) from non-EU countries into the EU or from a non-EU country to another non-EU country?                                                                                                                                                               |                                                                                                                                                                                                                         |         | X      | Details of the types of personal data and countries involved                                                                                                                                                                                                                                                                                                                  | Confirmation of compliance with the laws of the country in which the data was collected                                                                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Is it planned to export personal data (data transfer) from non-EU countries into the EU or from a non-EU country to another non-EU country?                                                                                                                                                               |                                                                                                                                                                                                                         |         | X      | Details of the types of personal data and countries involved                                                                                                                                                                                                                                                                                                                  | Confirmation of compliance with the laws of the country in which the data was collected                                                                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does your activity involve the processing of personal data related to criminal convictions or offenses?                                                                                                                                                                                                   |                                                                                                                                                                                                                         |         | X      |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6 THIRD COUNTRIES                                                                                                                                                                                                                                                                                         |                                                                                                                                                                                                                         |         |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Will some of the activities be carried out in non-EU countries?                                                                                                                                                                                                                                           |                                                                                                                                                                                                                         | X       |        | The consortium includes members located in Switzerland and in the UK, who follow the same legal frameworks and protection of data and ethical values as EU nations, therefore it is not deemed as a risk to have these organizations involved in some of the projects' tasks.                                                                                                 |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Do the activities undertaken in these countries raise potential ethics issues?                                                                                                                                                                                                                            |                                                                                                                                                                                                                         |         | X      | Countries/materials involved                                                                                                                                                                                                                                                                                                                                                  | Copies of ethics approvals and other authorisations or notifications (if required) and confirmation that the activity could have been legally carried <br>out in an EU country                                                                                                             |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Is it planned to use local resources? (e.g., animal/human tissue samples, genetic material, live animals, human remains, materials of historical value, endangered fauna/flora samples, etc.)                                                                                                             |                                                                                                                                                                                                                         |         | X      | Details on the type of local resources to be used and modalities                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Is it planned to import any material other than data from non-EU countries into the EU or from a non-EU country to another EU country?                                                                                                                                                                    |                                                                                                                                                                                                                         |         | X      | Countries/materials involved                                                                                                                                                                                                                                                                                                                                                  | Export licenses/Material Transfer Agreement (MTA)                                                                                                                                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Is it planned to export any material other than data from non-EU countries into the EU or from a non-EU country to another EU country?                                                                                                                                                                    |                                                                                                                                                                                                                         |         | X      | Countries/materials involved                                                                                                                                                                                                                                                                                                                                                  | Export licenses/Material Transfer Agreement (MTA)                                                                                                                                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does your activity involve low and/or lower-middle income countries?                                                                                                                                                                                                                                      |                                                                                                                                                                                                                         |         | X      |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ARTIFICIAL INTELLIGENCE AND OTHER ETHICAL ISSUES                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                         |         |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does this activity involve the development, deployment and/or use of Artificial Intelligence-based systems?                                                                                                                                                                                               |                                                                                                                                                                                                                         | X      |        | Machine learning classifiers will be used in WP2 to classify research articles, describing whether they are primary research and details of the experimental design and context. The classier will trained using human decisions by members of the consortium. We will describe how machine learning has been used to classify studies, including details of its performance. |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Could the AI based system/technique potentially stigmatise or discriminate against people (e.g. based on sex, race, ethnic or social origin, age, genetic features, disability, sexual orientation, language, religion or belief, membership to a political group, or membership to a national minority)? |                                                                                                                                                                                                                         | X       |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does the AI system/technique interact, replace or influence human decision-making processes (e.g. issues affecting human life, health, well-being or human rights, or economic, social or political decisions)?                                                                                           |                                                                                                                                                                                                                         | X       |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does the AI system/technique have the potential to lead to negative social (e.g. on democracy, media, labour market, freedoms, educational choices, mass surveillance) and/or environmental impacts either through intended applications or plausible alternative uses?                                   |                                                                                                                                                                                                                         | X       | X     |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does this activity involve the use of AI in a weapon system?                                                                                                                                                                                                                                              |                                                                                                                                                                                                                         | X      |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Does the AI to be developed/used in the Project raise any other ethical issues not covered by the questions above (e.g., subliminal, covert or deceptive AI, AI that is used to stimulate addictive behaviors, lifelike humanoid robots, etc.)?                                                           |                                                                                                                                                                                                                         | X       |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Are there any other ethics issues that should be taken into consideration? Please specify                                                                                                                                                                                                                 |                                                                                                                                                                                                                         | X      |        |                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
