on:
  push:
     branches:
       - main
  workflow_dispatch:

name: renderbook

jobs:
  bookdown:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[render]')
    name: Render-Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown", "metathis"))'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - name: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f docs/
          git commit -m 'Book built' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
