on:
  push:
     branches:
       - main
  workflow_dispatch:

name: renderbook

jobs:
  bookdown:
    if: contains(github.event.head_commit.message, '[deploy]')
    name: Render-Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v4
        with:
          name: _book
          path: _book/

  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v4
       with:
         name: _book
         # Destination path
         path: _book
     - name: Deploy to GitHub Pages
       uses: JamesIves/github-pages-deploy-action@v4
       env:
          token: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: _book/


